### ISSUE TITLE
Not all requests captured

### ISSUE THREAD

**Issue by craig** [caesar0301/http-sniffer#1]
Hi,

if you do "wget --mirror" of a huge site and run http-sniffer, it does not succeed in capturing all the requests.

**Comment by caesar0301** [comment]
Can you give more information about ur tests? Say the site name, protocols? I cannot catch details from your "huge".

**Comment by craig** [comment]
try sniffing all the requests from "wget --mirror www.heise.de"

**Comment by caesar0301** [comment]
Hi Craig,

I have test the mirror option and notice that multiple (to tens of) request/response pairs are carried by a single flow, thus the sniffer outputs single line of log (it actually does in this way).

If i missed something, please let me know. :)
Best,
Xiaming

**Comment by craig** [comment]
Yea, HTTP/1.1 works this way - it would be nice if you could fix your code?

**Comment by caesar0301** [comment]
I mean the http-sniffer has _exactly_ worked this way and the code needs no modification. It outputs multiple request/response pairs into one line if they are transferred by a single TCP flow.

If you want to extract individual HTTP request/response pair, you can write a small tool to extract those pairs from log line by line. Each line is stored in JSON.

Xiaming

**Comment by craig** [comment]
That won't work as not all requests are logged there. Too bad. :(

**Comment by caesar0301** [comment]
Could you send me a pcap file and your confusions? I can fix it.

Xiaming
